[book]
authors = ["Charles Poulmaire"]
language = "en"
multilingual = false
src = "src"
title = "Cours NSI"

[output.html]
git-repository-url = "https://github.com/charles-depot/Test-nsi"
mathjax-support = true

[output.html.print]
enable = false
