[book]
authors = ["Charles Poulmaire"]
language = "en"
multilingual = false
src = "src"
title = "Cours NSI"

[output.html]
git-repository-url = "https://github.com/fortierq/oc-m1-2021"
mathjax-support = true

[output.html.print]
enable = false
